### ISSUE TITLE
插件化apk的问题

### ISSUE THREAD

**Issue by YangHaoyi** [zdnuist/VirtualApkDemo#1]
最近公司项目也在考虑由组件化到插件化重构的问题，有个问题想请教一下，看你的README滴滴开源的这个会把主工程打包生成一个apk，同时再把插件打包一个apk push到sd卡中加载，我们在应用商店上架的都是一个apk，对于业务拆分后，不同业务应该是一个独立的apk，有提供给众多业务apk合并成一个上传给应用商店的工具么？还是需要配置方法？

**Comment by zdnuist** [comment]
你可以动态下载到本地 然后再加载
